In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([-0.65635975,  0.8691193 ,  0.49607009, -1.38279066,  0.46644985,
        0.08877059, -0.99250724,  1.64636268,  0.40646748, -3.34879059])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([ 0.03942127, -0.92991846,  0.36373466,  0.51979616,  0.65138158,
        0.13663524,  0.78665348, -1.0793706 , -0.13891455, -2.39643767])

In [10]:
np.add(A, B)

array([-0.61693848, -0.06079916,  0.85980475, -0.8629945 ,  1.11783143,
        0.22540583, -0.20585377,  0.56699208,  0.26755293, -5.74522826])

In [11]:
np.maximum(A, B)

array([ 0.03942127,  0.8691193 ,  0.49607009,  0.51979616,  0.65138158,
        0.13663524,  0.78665348,  1.64636268,  0.40646748, -2.39643767])