In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape((3,3))

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1, ser2, ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [12]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
pd.concat([ser1, ser2], axis=1, keys=['cat1', 'cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [15]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [16]:
dframe1

X         Y         Z
0 -1.079308 -1.161425 -0.069840
1 -0.012346  1.208134  1.017929
2  0.813731  0.354520 -2.346700
3  0.237439  1.124322 -1.212550

In [17]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [18]:
dframe2

Y         Q         X
0  0.188473 -0.701103 -0.039408
1  1.422900  0.353482 -0.218703
2 -0.553077  0.168888 -0.726163

In [19]:
pd.concat([dframe1, dframe2])

Q         X         Y         Z
0       NaN -1.079308 -1.161425 -0.069840
1       NaN -0.012346  1.208134  1.017929
2       NaN  0.813731  0.354520 -2.346700
3       NaN  0.237439  1.124322 -1.212550
0 -0.701103 -0.039408  0.188473       NaN
1  0.353482 -0.218703  1.422900       NaN
2  0.168888 -0.726163 -0.553077       NaN

In [20]:
pd.concat([dframe1, dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -1.079308 -1.161425 -0.069840
1       NaN -0.012346  1.208134  1.017929
2       NaN  0.813731  0.354520 -2.346700
3       NaN  0.237439  1.124322 -1.212550
4 -0.701103 -0.039408  0.188473       NaN
5  0.353482 -0.218703  1.422900       NaN
6  0.168888 -0.726163 -0.553077       NaN